plugins:
  - jekyll-seo-tag
title: Burley Summer Festival | Dog Show
description: Burley in Wharfedale Summer Festival Dog Show. Saturday 17th August 10:15-15:30.
url: https://burleysummerfestival.github.io/dogshow
author: Jordan Bowker
